version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: magnificentfox_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: magnificentfox_backend
    restart: always
    env_file:
      - .env  
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      gunicorn MagnificentFox.wsgi:application --bind 0.0.0.0:8000
      "

  db:
    image: mysql:8
    container_name: magnificentfox_db
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    container_name: magnificentfox_nginx
    restart: always
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
  static_volume:
  media_volume:
