version: "3.8"

services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: magnificentfox_web
    restart: always
    env_file:
      - .env  
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      gunicorn MagnificentFox.wsgi:application --bind 0.0.0.0:8000
      "

  db:
    image: mysql:8
    container_name: magnificentfox_db
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # Required!
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: magnificentfox_nginx
    restart: always
    ports:
      - "8080:80"   # HTTP port
      - "443:443"   # HTTPS port
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web

volumes:
  db_data:
  static_volume:
  media_volume:
