# Generated by Django 5.1.7 on 2025-04-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="productvideo",
            name="video_url",
        ),
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                default="product_images/default.jpg", upload_to="product_images/"
            ),
        ),
        migrations.AddField(
            model_name="productvideo",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="product_videos/"),
        ),
    ]
